config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  resources :appointments, only: [:edit, :index, :update, :new, :create]
  match '/patients/profile/:id', to: 'patients#show', via: 'get'
  match '/doctors', to: 'doctors#index', via: 'get'
  match '/doctors/search', to: 'doctors#search', via: 'get'
  match '/doctors/profile/:id', to: 'doctors#show', via: 'get'
  devise_for :admins, path: 'admins', controllers: {
        sessions: 'admins/sessions', registrations: 'admins/registrations'
      }
  devise_for :doctors, path: 'doctors', controllers: {
        sessions: 'doctors/sessions', registrations: 'doctors/registrations'
      }
  devise_for :patients, path: 'patients', controllers: {
        sessions: 'patients/sessions', registrations: 'patients/registrations'
      }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :redirect_when_logged_in

	def index
		
	end

	def redirect_when_logged_in
		if doctor_signed_in?
			redirect_to "/doctors/profile/#{current_doctor.id}"
		elsif patient_signed_in?
			redirect_to "/patients/profile/#{current_patient.id}"
		end		
	end

end

app/views/home/_header.html.erb
<div class="header">
	<ul>
		<% unless patient_signed_in? or doctor_signed_in? %>
			<li class="hoverable">
				<%= link_to "Home", root_path %>
			</li>
		<% end %>

		<% if patient_signed_in? %>
			<li class="hoverable">
				<%= link_to 'My Profile', "/patients/profile/#{current_patient.id}" %>
			</li>
		<% end %>
		<% if doctor_signed_in? %>
			<li class="hoverable">
				<%= link_to 'My Profile', "/doctors/profile/#{current_doctor.id}" %>
			</li>
		<% end %>
		<% if doctor_signed_in? or patient_signed_in? %>
			<li class="hoverable">
				<%= link_to 'My appointments', appointments_path %>
			</li>
		<% end %>
		<% if doctor_signed_in? or patient_signed_in? %>
			<li class="hoverable">
				<%= link_to "Search", doctors_path %>
			</li>
		<% end %>
		<% if patient_signed_in? %>
			<li class="hoverable">
				<%= link_to "Log out", destroy_patient_session_path, method: :delete %>
			</li>
		<% end %>	
		<% if doctor_signed_in? %>
			<li class="hoverable">
				<%= link_to "Log out", destroy_doctor_session_path, method: :delete %>
			</li>
		<% end %>
		<% if admin_signed_in? %>
			<li class="hoverable">
				<%= link_to "Log out", destroy_admin_session_path, method: :delete %>
			</li>
		<% end %>
		
		<li class="logo_header">OffClinic ✚ </li>
	</ul>
</div>

app/views/home/index.html.erb
<div class="info">
	<div>OffClinic is a convenient place to find your doctor and apply for appointment.</div>
	<div>We are always happy to see you here, but hope you won't need to visit us too often.</div>
	<div class="donations">We also accept blood donations 🩸</div>
</div>
<%= link_to "Log in", new_patient_session_path, class:"home-button login-button" %>
<%= link_to "Register", new_patient_registration_path, class:"home-button register-button" %>
<div class="usagi"><%= image_tag 'nurseusagi.jpg', style: 'height:300px;width:auto;' %></div>