config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  resources :appointments, only: [:edit, :index, :update, :new, :create]
  match '/patients/profile/:id', to: 'patients#show', via: 'get'
  match '/doctors', to: 'doctors#index', via: 'get'
  match '/doctors/search', to: 'doctors#search', via: 'get'
  match '/doctors/profile/:id', to: 'doctors#show', via: 'get'
  devise_for :admins, path: 'admins', controllers: {
        sessions: 'admins/sessions', registrations: 'admins/registrations'
      }
  devise_for :doctors, path: 'doctors', controllers: {
        sessions: 'doctors/sessions', registrations: 'doctors/registrations'
      }
  devise_for :patients, path: 'patients', controllers: {
        sessions: 'patients/sessions', registrations: 'patients/registrations'
      }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments
  has_many :patients, through: :appointments
  belongs_to :category
  delegate :name, to: :category, prefix: true
  validates :category_id, presence: true
  validates :name, presence: true, length: { maximum: 150 }
  validates :description, length: { maximum: 1500 }
  mount_uploader :avatar, AvatarUploader
end

app/controllers/doctors/confirmations_controller.rb
# frozen_string_literal: true

class Doctors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/doctors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Doctors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/doctors/passwords_controller.rb
# frozen_string_literal: true

class Doctors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true

class Doctors::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_role, except: [:new, :create]

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors/sessions_controller.rb
# frozen_string_literal: true

class Doctors::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_role, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/doctors/unlocks_controller.rb
# frozen_string_literal: true

class Doctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_a_user
  load_and_authorize_resource

  def index
    @doctors = Doctor.all
    @category = Category.first
  end

  def show
	  @doctor = Doctor.find_by_id(params[:id])
  end

  def search
  	@doctors = Doctor.where("category_id = ?", params[:category_id])
  	@category = Category.find_by_id(params[:category_id])
  end

end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_search.html.erb
<h2 class="search_doctor">Please select a doctor category:
<%= form_with url: doctors_search_path, method: :get do |form| %>
  <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name, @category.id) %>
  <%= form.submit "Search" %>
<% end %></h2>

app/views/doctors/index.html.erb
<%= render 'search' %>

<% @doctors.each do |doctor| %>
<div class="doctor_list_element">
	<%= avatar_for(doctor) %>
	<div class="doctor_list_info"><%= doctor.name %> | <%= doctor.category_name.capitalize %> | <%= doctor.email %></div> 
	<%= link_to 'Show', "/doctors/profile/#{doctor.id}", class:"list_pink_button" %>
</div>
<% end %>

app/views/doctors/search.html.erb
<%= render 'search' %>

<% if @doctors.size < 1 %>
	<div class="no_results">No results</div>
<% else %>
	<% @doctors.each do |doctor| %>
		<div class="doctor_list_element">
			<%= avatar_for(doctor) %>
			<div class="doctor_list_info"><%= doctor.name %> | <%= doctor.category_name.capitalize %> | <%= doctor.email %></div> 
			<%= link_to 'Show', "/doctors/profile/#{doctor.id}", class:"list_pink_button" %>
		</div>
	<% end %>
<% end %>

app/views/doctors/show.html.erb
<div class="profile_form_wrapper doctor_form_wrapper ">
	<h2 class="profile_head">Doctor Profile</h2>

	<div class="profile_elements">
		<div class="profile-avatar">
			<div class="avatar-border">
				<%= avatar_for(@doctor) %>
			</div>
		</div>
		<div class="profile_info">
			<h2><%= @doctor.name %> | <%= @doctor.category.name.capitalize %></h2>
			<div><b>Email: </b><%= @doctor.email%></div>
			<div><b>Description: </b><%= (@doctor.description && @doctor.description.size > 0) ? @doctor.description : "No description" %></div>
		</div>
	</div>
	<% if @doctor == current_doctor %>
		<div class="hoverable profile_button"><%= link_to "Edit profile", edit_doctor_registration_path %></div>
	<% end %>
	<% if patient_signed_in? %>
		<div class="hoverable profile_button"><%= link_to "Apply", new_appointment_path(:doctor_id => @doctor.id) %></div>
	<% end %>
</div>