config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/administration', as: 'rails_admin'
  resources :appointments, only: [:edit, :index, :update, :new, :create]
  match '/patients/profile/:id', to: 'patients#show', via: 'get'
  match '/doctors', to: 'doctors#index', via: 'get'
  match '/doctors/search', to: 'doctors#search', via: 'get'
  match '/doctors/profile/:id', to: 'doctors#show', via: 'get'
  devise_for :admins, path: 'admins', controllers: {
        sessions: 'admins/sessions', registrations: 'admins/registrations'
      }
  devise_for :doctors, path: 'doctors', controllers: {
        sessions: 'doctors/sessions', registrations: 'doctors/registrations'
      }
  devise_for :patients, path: 'patients', controllers: {
        sessions: 'patients/sessions', registrations: 'patients/registrations'
      }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/views/layouts/_iam_login.html.erb
<div class="iam_wrapper">
<%= link_to "I'm a patient", new_patient_session_path, class:"login-button iam_patient iam_button" %><%= link_to "I'm a doctor", new_doctor_session_path, class:"register-button iam_doctor iam_button" %>
</div>

app/views/layouts/_iam_register.html.erb
<div class="iam_wrapper">
<%= link_to "I'm a patient", new_patient_registration_path, class:"login-button iam_patient iam_button" %><%= link_to "I'm a doctor", new_doctor_registration_path, class:"register-button iam_doctor iam_button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Offclinic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>